# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 34dfb8092f162070a7cb223d71ec9968895536f9daa080cac01e4430537571ec53c9221d2d6d31d38cf900d57d8d2ac945e015f77a7af32bb727ff559100a753

test:
  secret_key_base: 127ef1e808fe3f8e519ca9028fed056d780576233a273bfdb12df6e08ac22622f2eed7329333e16dfde49b85c307bd72b68750b6c834f33f6ef6c5496ee885bd

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
